variable "aws_region" {}
variable "regionDefault" {}
variable "cluster_name" {}
variable "cluster_version" {}
variable "projectName" {}
variable "nodeGroup" {}
variable "role" {}
variable "instanceType" {}
variable "s3_bucket_name" {}
