name: Observe EKS

on:
  workflow_run:
    workflows: ["Terraform Deploy"]  # deve ser exatamente o mesmo `name:` do deploy.yml
    types:
      - completed

jobs:
  observe:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: observe

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Autenticar na AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Criar backend.tf para observar o estado remoto
        run: |
          cat <<EOF > backend.tf
          terraform {
            backend "s3" {
              bucket = "terraform-pipeline-bucket-361598269712"
              key    = "infra/terraform.tfstate"
              region = "us-east-1"
              encrypt = true
            }
          }
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Observação)
        run: terraform plan
