name: Observe EKS

on:
  workflow_run:
    workflows: ["Terraform Deploy"]
    types:
      - completed

jobs:
  observe:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: observe

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Autenticar na AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Import aws-auth ConfigMap (somente se necessário)
        run: |
          terraform state show kubernetes_config_map.aws_auth >/dev/null 2>&1 || \
          terraform import kubernetes_config_map.aws_auth kube-system/aws-auth

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan || {
            echo "::warning::Sem alterações detectadas no plano. Prosseguindo com apply (se necessário)."
            exit 0
          }

      - name: Terraform Apply
        run: terraform apply -auto-approve || {
          echo "::warning::Nada foi aplicado, pois não houve mudanças reais."
          exit 0
          }
